### ISSUE TITLE
make errors out on master

### ISSUE THREAD

**Issue by hhuuggoo** [HDI-Project/FeatureHub#10]
cp: cannot stat _../share/static/images/featurehub.png_: No such file or directory

**Comment by hhuuggoo** [comment]
it's easy to work around , but figure I'd file an issue

**Comment by micahjsmith** [comment]
Can you provide context please as well as your work around? Thanks

**Comment by hhuuggoo** [comment]
Oh, my workaround was just to copy 

https://github.com/HDI-Project/FeatureHub/blob/master/share/static/images/featurefactory.png

to featurehub.png in the same directory

this is the result of running $ sudo make build inside this directory:

https://github.com/HDI-Project/FeatureHub/tree/master/deploy

**Comment by micahjsmith** [comment]
Fixed, thanks
