### ISSUE TITLE
scipy error during make build?

### ISSUE THREAD

**Issue by hhuuggoo** [HDI-Project/FeatureHub#11]
Not sure what to do about this one

Installing collected packages: scipy, smac
  Found existing installation: scipy 0.17.1
Cannot uninstall 'scipy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.                                                                                                                                                  
ERROR: Service 'user' failed to build: The command '/bin/sh -c wget -q -O- https://raw.githubusercontent.com/automl/auto-sklearn/v.0.2.0/requirements.txt | xargs -n 1 -L 1 /opt/conda/bin/pip install' returned a non-zero code: 123
make: *** [build_static] Error 1

Any feedback would be helpful.  This is done using the Amazon AMI, amzn-ami-hvm-2018.03.0.20180622-x86_64-gp2 (ami-40142d25), and it's being run as root

**Comment by micahjsmith** [comment]
Can you provide some context? Your `pwd` as well as the sequence of commands you ran. Thanks.

**Comment by hhuuggoo** [comment]
Yup - the pwd is

~/FeatureHub/deploy

and the command is just 

$ sudo make build

the previous commands were 

$ yum install git
$ git clone https://github.com/HDI-Project/FeatureHub.git
$ yum install docker
$ sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose

then I tweaked the config
and then
$ cd FeatureHub/deploy
$ make build

**Comment by micahjsmith** [comment]
Looks like some python packages that were not pinned have been updated and are now incompatible. I will try to debug.

**Comment by micahjsmith** [comment]
Try with latest master (72051a73240fbec5ebc150fdfa48cd1418697475), I'm able to `make build` from a fresh AMI with these changes.

**Comment by hhuuggoo** [comment]
cool thanks
