### ISSUE TITLE
Failed to build image from deploy folder due to dependencies conflicts.

### ISSUE THREAD

**Issue by liudongqing** [HDI-Project/FeatureHub#12]
I tried to follow the installation guide and make build, got the following error.

> Installed /opt/conda/lib/python3.5/site-packages/featurehub-0.3.0-py3.5.egg
> Processing dependencies for featurehub==0.3.0
> error: prompt-toolkit 2.0.5 is installed but prompt-toolkit<2.0.0,>=1.0.3 is required by {'ipython'}
> ERROR: Service 'user' failed to build: The command '/bin/sh -c cd /tmp/featurehub/src && /opt/conda/bin/python setup.py install' returned a non-zero code: 1
> make: *** [build_static] Error 1

Check the log and find the following information:
>Collecting prompt-toolkit<2.1.0,>=2.0.0 (from jupyter-console->jupyter->-r /tmp/featurehub/requirements.txt (line 4))
>Requirement already satisfied: wcwidth in /opt/conda/lib/python3.5/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter->-r /tmp/featurehub/requirements.txt (line 4))

attached the log after step 13 for checking. [cosole.log](https://github.com/HDI-Project/FeatureHub/files/2544867/cosole.log)

Thanks.

**Comment by micahjsmith** [comment]
Thanks for the PR!
